### ISSUE TITLE
Typo in Demystifying LLMs

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#513] opened 2023-08-11 14:58 UTC
record number: 620 

Description of issue: Typo reported on the page discussing vectorization (page 6). Learner couldn't remember exactly where/what the typo was.

**Comment by franzenr** [comment] 2023-08-11 21:49
Tried to find a typo on that page, and came up short...

The only thing I could think of (after seeing that they mentioned they thought it was toward the top of the page) is perhaps the final bullet in the tl;dr 
> Advances in language modeling **required** the use of neural networks.
(emphasis mine) 

While there's technically nothing grammatically incorrect with this sentence, it did stick out at me. Perhaps they were confused by the use of past tense here, and think it should be "require" ?? That being said, I know @pm0kjp was approaching this as a "historical background of the evolution of LLMs", so I think perhaps the past tense may have been intentional? 

Curious what others think and if anyone else is better able to locate a typo. If people aren't convinced about trying to change required --> require, I think it's also probably fine to just flag this as "can't reproduce" , and hopefully if someone else notices it, they'll remember a bit more detail about where it was!

**Comment by pm0kjp** [comment] 2023-08-17 14:40
We can't find the typo, won't fix at this time.

**Closed by pm0kjp** 2023-08-17 14:40 UTC
Labels: typo, user-reported, cant replicate, Demystifying Large Language Models
