### ISSUE TITLE
Code blocks appearing on the wrong page

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#747] opened 2023-10-17 12:59 UTC
record number: 1681

Description of problem: User reports that code blocks seem to appear a page before the corresponding text.

---

**Some things to try first!** 

- If pyodide cells aren't working as expected in Python modules, we may need to update pyodide. 
- If LiaScript macros aren't rendering properly, especially `overview`, check for blank macros defined in the front matter (e.g.`version_history` is a common culprit). You may need to add load bearing white space. 
- If the `feedback` macro isn't working, check that no front matter fields used in the generated REDCap link are missing (e.g. `module_type`).
- Problems with `div`? You may need a newline after the `div` tag and before the `/div` tag. 
- Quiz answer boxes not displaying properly? There cannot be a newline between the last answer option and the beginning of the question followup section. Make sure the `****` surrounding the answer div starts immediately after the last line of the question.

**Comment by rosemm** [comment] 2023-10-17 16:55
I am successfully replicating this in chrome. For me, the problems begin at https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/sql_basics/sql_basics.md#9

**Comment by pm0kjp** [comment] 2023-11-17 16:58
I can't reproduce this error, @rosemm can you, still?  Can you grab a screenshot to show me what you see?  To me the tables all line up as expected.

**Comment by rosemm** [comment] 2023-11-17 17:09
I think this may have been a temporary bug that was fixed in some update to Chrome and/or LiaScript. I do still see the weird behavior when I open in Chrome (see screenshot below), but I think that's cached. It looks correct now if I open in incognito or with firefox. 

<img width="1781" alt="Screenshot 2023-11-17 at 12 07 43 PM" src="https://github.com/arcus/education_modules/assets/9002194/182450bf-16d9-4ed4-a53a-a29d30a7f896">

**Comment by pm0kjp** [comment] 2023-11-20 15:07
I think some of this was due to Liascript caching (and need to upversion).  Will keep pushing on this...

**Comment by leemc-data-ed** [comment] 2023-12-15 15:19
I couldn't replicate this, this seems to have been solved by an update at some point. I think we're good to close.

**Closed by leemc-data-ed** 2023-12-15 15:19 UTC
Labels: bug, user-reported, SQL Basics, :fire: Urgent! :fire:
