### ISSUE TITLE
Code being pre-run is confusing

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/education_modules#815] opened 2023-11-21 21:38 UTC
record number: 1901

Description of issue: A learner points out that on page 19 ("Edit existing columns"), the "female" entries have already been changed to "F" before you explicitly perform that step; I think this is due to all of the code chunks being pre-run, so when the leaner prints the output of the second code chuck, it already reflects changes that are made in the third. They were confused as to what task they were supposed to be doing.

**Comment by rosemm** [comment] 2023-11-22 14:26
Looks like a duplicate of #647

**Closed** 2023-12-20 20:16 UTC
Labels: bug, user-reported, Transform Data with pandas
